-- migrate:up
ALTER TABLE bookings_seats
ADD COLUMN booking_time DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


-- migrate:down

